const Favorites = () => {
  return (
    <div>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
      <p>Favorites</p>
    </div>
  );
};

export default Favorites;
